global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'samagya.sap@gmail.com'
  smtp_auth_username: 'samagya.sap@gmail.com'
  smtp_auth_password: 'jumt beeh nnjo bbtq'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'samagya.sap@gmail.com'
        send_resolved: true
        headers:
          Subject: 'ðŸš¨ Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Alert Details</h2>
          <p><b>Alert:</b> {{ .GroupLabels.alertname }}</p>
          <p><b>Severity:</b> {{ .CommonLabels.severity }}</p>
          <p><b>Summary:</b> {{ .CommonAnnotations.summary }}</p>
          <p><b>Description:</b> {{ .CommonAnnotations.description }}</p>
